# Generated by Django 4.2.2 on 2023-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='attendees',
        ),
        migrations.AddField(
            model_name='topics',
            name='related_topics',
            field=models.ManyToManyField(blank=True, to='main.topics'),
        ),
    ]
